### Model evaluation and improvement




Để đánh giá chất lượng  của một mô hình chúng ta phân  chia dữ liệu thành hai phần bằng hàm **train_test_split()** trong đó mô hình được xây dựng  trên  bộ dữ liệu huấn luyện bằng hàm **fit()** và mô hình được đánh giá trên bộ dữ liệu kiểm định với hàm **score()**. Xét một ví dụ đơn giản sau: 



In [87]:
# Load gói pandas và đọc vào dữ liệu: 
import pandas as pd
credit = pd.read_csv("C:/Users/win10ls/Desktop/Data_Science/credit.csv")

# Xem qua dữ liệu: 
credit.shape

(30000, 25)

In [88]:
# Một số quan sát đầu: 
credit.head()


id      X1  X2  X3  X4  X5  X6  X7  X8  X9 ...    X15    X16    X17   X18  \
0   1   20000   2   2   1  24   2   2  -1  -1 ...      0      0      0     0   
1   2  120000   2   2   2  26  -1   2   0   0 ...   3272   3455   3261     0   
2   3   90000   2   2   2  34   0   0   0   0 ...  14331  14948  15549  1518   
3   4   50000   2   2   1  37   0   0   0   0 ...  28314  28959  29547  2000   
4   5   50000   1   2   1  57  -1   0  -1   0 ...  20940  19146  19131  2000   

     X19    X20   X21   X22   X23  Y  
0    689      0     0     0     0  1  
1   1000   1000  1000     0  2000  1  
2   1500   1000  1000  1000  5000  0  
3   2019   1200  1100  1069  1000  0  
4  36681  10000  9000   689   679  0  

[5 rows x 25 columns]

In [89]:
# Loại cột biến id: 
credit.drop("id", axis = 1, inplace = True)
credit.head()

X1  X2  X3  X4  X5  X6  X7  X8  X9  X10 ...    X15    X16    X17   X18  \
0   20000   2   2   1  24   2   2  -1  -1   -2 ...      0      0      0     0   
1  120000   2   2   2  26  -1   2   0   0    0 ...   3272   3455   3261     0   
2   90000   2   2   2  34   0   0   0   0    0 ...  14331  14948  15549  1518   
3   50000   2   2   1  37   0   0   0   0    0 ...  28314  28959  29547  2000   
4   50000   1   2   1  57  -1   0  -1   0    0 ...  20940  19146  19131  2000   

     X19    X20   X21   X22   X23  Y  
0    689      0     0     0     0  1  
1   1000   1000  1000     0  2000  1  
2   1500   1000  1000  1000  5000  0  
3   2019   1200  1100  1069  1000  0  
4  36681  10000  9000   689   679  0  

[5 rows x 24 columns]

In [90]:
# Hồ sơ được đánh số 1 = Default và 0 = NonDefault: 
credit.Y.unique()

array([1, 0], dtype=int64)

In [91]:
# Dán lại nhãn cho cột biến Y: 
Y = credit["Y"]
Y[Y == 1] = "B"
Y[Y == 0] = "G"
# Thay thế Y mới ở trên: 
credit = credit.assign(Y = Y)

In [92]:
credit.head()

X1  X2  X3  X4  X5  X6  X7  X8  X9  X10 ...    X15    X16    X17   X18  \
0   20000   2   2   1  24   2   2  -1  -1   -2 ...      0      0      0     0   
1  120000   2   2   2  26  -1   2   0   0    0 ...   3272   3455   3261     0   
2   90000   2   2   2  34   0   0   0   0    0 ...  14331  14948  15549  1518   
3   50000   2   2   1  37   0   0   0   0    0 ...  28314  28959  29547  2000   
4   50000   1   2   1  57  -1   0  -1   0    0 ...  20940  19146  19131  2000   

     X19    X20   X21   X22   X23  Y  
0    689      0     0     0     0  B  
1   1000   1000  1000     0  2000  B  
2   1500   1000  1000  1000  5000  G  
3   2019   1200  1100  1069  1000  G  
4  36681  10000  9000   689   679  G  

[5 rows x 24 columns]

In [93]:
y = Y
y.head()

0    B
1    B
2    G
3    G
4    G
Name: Y, dtype: object

In [94]:
X = credit.drop("Y", 1)
X.head()

X1  X2  X3  X4  X5  X6  X7  X8  X9  X10  ...     X14    X15    X16  \
0   20000   2   2   1  24   2   2  -1  -1   -2  ...     689      0      0   
1  120000   2   2   2  26  -1   2   0   0    0  ...    2682   3272   3455   
2   90000   2   2   2  34   0   0   0   0    0  ...   13559  14331  14948   
3   50000   2   2   1  37   0   0   0   0    0  ...   49291  28314  28959   
4   50000   1   2   1  57  -1   0  -1   0    0  ...   35835  20940  19146   

     X17   X18    X19    X20   X21   X22   X23  
0      0     0    689      0     0     0     0  
1   3261     0   1000   1000  1000     0  2000  
2  15549  1518   1500   1000  1000  1000  5000  
3  29547  2000   2019   1200  1100  1069  1000  
4  19131  2000  36681  10000  9000   689   679  

[5 rows x 23 columns]

In [98]:
# Phân chia dữ liệu theo tỉ lệ 50 - 50: 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 29)

In [99]:
len(y_train)

15000

In [100]:
len(y_test)

15000

In [109]:
# Thực hiện hồi quy Logistic: 
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression().fit(X_train, y_train)

# Đánh giá chất lượng của  mô hình dự báo: 
logreg.score(X_test, y_test)


0.77900000000000003

In [114]:
# So sánh để thấy tỉ lệ dự báo này trên mẫu thử nghiệm là không cao đáng kể so với đoán ngẫu nhiên: 
sum(Y == "G") / len(y)

0.7788

In [120]:
# Thực hiện cross-validation (mặc định k = 3) với đảm  bảo là phân phối của
# biến  đích không đổi (stratifed k-fold cross-validation)
from sklearn.model_selection import cross_val_score
logreg = LogisticRegression()
scores = cross_val_score(logreg, X, Y)
print("Cross-validation accuracy: ", scores)

Cross-validation accuracy:  [ 0.7787  0.7788  0.7786]


In [136]:
# Chọn k = 5: 
scores5 = cross_val_score(logreg, X, Y, cv = 5)
scores5

array([ 0.77870355,  0.779     ,  0.77883333,  0.77883333,  0.77879647])

In [135]:
#  Tính mean: 
scores5.mean()

0.77883333643055563

In [141]:
# Một cách khác với lựa chọn shuffle = True để khắc phục vấn dề phân phối của biến đích:  
from sklearn.model_selection import KFold
kfold = KFold(n_splits = 5, random_state = 9, shuffle = True)
cross_val_score(logreg, X, Y, cv = kfold)

array([ 0.77983333,  0.77716667,  0.78183333,  0.779     ,  0.77583333])

###  Cái này hay ngâm cú ngay

In [144]:
import numpy as np

np.random.seed(10)
X = pd.DataFrame({"Income": np.random.randint(1, 11, 20),
                  "Exp": np.random.randint(1, 11, 20)})

X

Exp  Income
0     5      10
1     2       5
2     4       1
3     7       2
4     6      10
5     4       1
6    10       2
7     7       9
8    10      10
9     2       1
10   10       9
11    5       7
12    3       5
13    7       4
14    8       1
15    9       5
16    9       7
17   10       9
18    3       2
19    1       9

In [147]:
y = (X["Income"] + X["Exp"]).map(lambda x: 1 if x <= 10 else 0)
y

0     0
1     1
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    0
11    0
12    1
13    0
14    1
15    0
16    0
17    0
18    1
19    1
dtype: int64

In [148]:
z = (X["Income"] + X["Exp"]).map(lambda x: "B" if x <= 10 else "G")
z

0     G
1     B
2     B
3     B
4     G
5     B
6     G
7     G
8     G
9     B
10    G
11    G
12    B
13    G
14    B
15    G
16    G
17    G
18    B
19    B
dtype: object